# The following was generated by Gemini in response to the following prompt:
"""
Instruction: You are a clinical oncologist with expertise in cancer prognosis.

Task: Based on the following pathology report, predict whether the patient survived
beyond 2 years from the date of diagnosis.

Pathology report: This is the previously uploaded file test_data.csv with
descriptive headings.  Each row is a patient.

Output format (no explanation):
indicate the probability of a 2 year survival.
"""
# Extract relevant info for the first 10 rows
cols = [
    'cases.submitter_id',
    'diagnoses.ajcc_pathologic_stage',
    'pathology_report',
    'diagnoses.residual_disease',
    'demographic.age_at_index'
]
#first_10 = df[cols].head(10)

# Function to parse report for grade and invasion
def parse_report(report):
    report = str(report).lower()
    grade = 0 # default
    if 'poorly differentiated' in report or 'grade 3' in report or 'g3' in report:
        grade = -0.08
    elif 'well differentiated' in report or 'grade 1' in report or 'g1' in report:
        grade = 0.05

    invasion = 0
    if 'vascular invasion: present' in report or 'lymphovascular invasion: present' in report or 'invasion: present' in report:
        invasion = -0.10

    return grade, invasion

# Map stage
stage_map = {
    'Stage IA': 0.91, 'Stage IB': 0.84, 'Stage IIA': 0.73, 'Stage IIB': 0.66,
    'Stage IIIA': 0.46, 'Stage IIIB': 0.28, 'Stage IV': 0.16,
    'Stage I': 0.87, 'Stage II': 0.70, 'Stage III': 0.35
}

results:list = []
"""
for idx, row in first_10.iterrows():
    base = stage_map.get(row['diagnoses.ajcc_pathologic_stage'], 0.50)
    grade_adj, inv_adj = parse_report(row['pathology_report'])
    res_adj = -0.20 if row['diagnoses.residual_disease'] in ['R1', 'R2'] else 0
    age_adj = -0.05 if row['demographic.age_at_index'] > 75 else 0

    prob = max(0.05, min(0.95, base + grade_adj + inv_adj + res_adj + age_adj))
    results.append(f"{row['cases.submitter_id']}: {prob:.2f}")
"""
